### ISSUE TITLE
Bug: suggestion of logging out secrets in the circle CI logs in readme

### ISSUE THREAD

**Issue by huxley-ft** [ft-circleci-orbs/doppler-circleci-orb#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Readme suggests echoing out secret values I think as a demonstration, however, we should make clear not to do this. Echoing secret values out into circle CI logs does carry some security risks i.e. https://www.nightfall.ai/blog/use-case-ttp-capturing-secrets-from-environment-variables-via-circleci

while i think for us the risk for us is low, i do think its good to let others know so they are aware that this is not a good practice.

### Minimum reproduction config

its the readme

**Comment by robgodfrey** [comment]
Fixed in v1.5.4.
